### ISSUE TITLE
0.3-wip: Spec shuffling breaks xctool test integration

### ISSUE THREAD

**Issue by dmrschmidt** [specta/specta#101]
The new test shuffling added a print statement for the seed in use here https://github.com/specta/specta/commit/bcba04d57fd05ce1a7ce110d998d8363053da0ef#diff-a5a40de00f424fc4d014f7dba24ba7c5R76

When xctool gets the list of all tests to run, this print end ups at the end of the JSON array which contains all those tests. As a result it can't parse the array and exits with "Failed to query the list of test cases in the test bundle: Error while parsing JSON: The data is not in the correct format.".

So the seed that was used should probably be output differently.

**Comment by orta** [comment]
Closing, looks resolved.
