### ISSUE TITLE
itShouldBehaveLike being called prior to beforeAll/beforeEach

### ISSUE THREAD

**Issue by NSDex** [specta/specta#103]
Consider the following:
```
SpecBegin(...)
__block NSObject *importantObjectThatNeedsToBeCreated = nil;
beforeAll(^{
  importantObjectThatNeedsToBeCreated = [[NSObject alloc] init];
});

itShouldBehaveLike(@"some shared example", ^{
  return @{@"inputObject": importantObjectThatNeedsToBeCreated};
});
SpecEnd
```

"some shred example" will execute with nil input before the beforeAll (and even the block passed to itShouldBehaveLike).

**Comment by modocache** [comment]
@NSDex @hatunike Can you show the full code for your `sharedExamples(@"some shared example")`? As @akashivskyy mentions, it's possible you're accessing variables before Specta expects you to.

**Comment by NSDex** [comment]
@modocache: I migrated to a different approach after hitting this issue and don't have the bandwidth to recreate the problem at this time.  Feel free to close unless @hatunike or @akashivskyy can provide the details you need.

**Comment by paweldudek** [comment]
@NSDex I've prepared a [sample test](https://github.com/paweldudek/specta/blob/0ef5c3f501a82fecb0487bbe60aaf3544b120824/Specta/SpectaTests/SharedExamplesTest7.m) that should fail if `sharedExamples` would have an issue that you described but everything appears to be working just fine. 

@robb looks like you can close this one, unless there's someone who can provide a broken sample project :wink:

**Comment by hatunike** [comment]
I ended up fixing mine, and it was related to what @akashivskyy  shows above. I originally fixed it by just creating a new file and just slowly copied everything over, trying to see what the issue was. Not sure how well documented this issue is, but I'd imagine many others will make this mistake. Thanks.

**Comment by modocache** [comment]
Looks like this can be closed! I'll keep this in mind when improving documentation in the future. Thanks, everybody! :+1:
