### ISSUE TITLE
[Question] Is there a way to jump to test definition?

### ISSUE THREAD

**Issue by squarefrog** [specta/specta#104]
Is there a way to jump to a failing test from the test navigator, like when using Kiwi/XCTest?

1. Run all tests
2. Observe a test fail
3. Click the test string in the navigator e.g. "ViewController_test_should_fail"
4. Xcode jumps to the failing test in the main editor window

**Comment by orta** [comment]
This is working for me in Xcode 6.1.1

![screen shot 2015-02-10 at 5 35 51 pm](https://cloud.githubusercontent.com/assets/49038/6137974/4a35cf96-b14b-11e4-9f03-d9a9d3d5b889.png)

**Comment by mickeyreiss** [comment]
I also experience this failure intermittently, as well as a failure to list all test names in the Test Navigator.

**Comment by orta** [comment]
I don't think there's much Specta can do to improve this though this issue specifically is an Expecta issue, it uses all the official APIs for failing with lines/files.  Specta generating test cases that conform to how XCTest would, I think the flakiness is basically Xcode.

**Comment by squarefrog** [comment]
As an update, when this stops working, the following fix works for me:

1. Clean the project
2. Clean build folder
3. Restart Xcode
4. Re-run full suite of tests

I've yet to narrow down what exactly causes the issue in the first place.
