### ISSUE TITLE
Performance tests support

### ISSUE THREAD

**Issue by pepibumur** [specta/specta#107]
With iOS 8 a new feature introduced in tests was the **performance tests**. I think it would be great to have support to these tests using 

```swift
func testDateFormatterPerformance() {
    let dateFormatter = NSDateFormatter()
    dateFormatter.dateStyle = .LongStyle
    dateFormatter.timeStyle = .ShortStyle
    let date = NSDate()
    self.measureBlock() {
        let string = dateFormatter.stringFromDate(date)
    }
}
```

Like this is not something related with **expectations** I think we could try another syntax for this case. Something like:
```swift
measure {
 let string = dateFormatter.stringFromDate(date)
}
```
Where in case of Swift we use closures to pass the operations to be executed in this measuring block.
Thoughts?

**Comment by orta** [comment]
This might fit better as a custom Expecta matcher :+1: - check some [examples here](http://cocoapods.org/?q=expecta)
