### ISSUE TITLE
Testing UIViewController presentedViewController returns nil

### ISSUE THREAD

**Issue by slhodson969** [specta/specta#111]
I am using Specta to create some tests but I don't seem to be able to get this basic one to pass. The app itself works fine but this test won't pass.

**ViewController**

    - (void)viewDidAppear:(BOOL)animated {
        [super viewDidAppear:animated];
        [self showLogin];
    }
    
    - (void)showLogin
	{
    	[self presentViewController:[ETLoginVC new] animated:NO completion:nil];
    	NSLog(@"PresentedVC: %@", [self.presentedViewController class]);
	}

This logs: `PresentedVC: ETLoginVC`

**Specs**
    
    SpecBegin(ETLoadingVCSpec)
    
    describe(@"ETLoadingVC", ^{
        __block ETLoadingVC *loadingVC;
    
        beforeEach(^{
            loadingVC = [[ETLoadingVC alloc] initWithUserDefaults:nil];
        });
    
        afterEach(^{
            loadingVC = nil;
        });
    
        describe(@"no current user present", ^{
            it(@"should have a login view controller as the presented view controller", ^{
                expect(loadingVC.presentedViewController).to.beKindOf([ETLoginVC class]);
            });
        });
    });
    
    SpecEnd
    
This fails with: `the actual value is nil/null`

I also tried adding:

    [viewController view];
   
and:

	[viewController viewWillAppear:NO];
	
But still no success in getting the expected value for the `presentedViewController`

Am I doing something wrong here?

**Comment by orta** [comment]
I think this is off topic, plus pretty much resolved. Closing.

**Comment by mchirino89** [comment]
> Is the view controller hierarchy connected to a `UIWindow` in any way?

Almost a decade later, this comment saved my 🍑 (in Swift). In case someone finds it useful, this is how I did it

```swift
func test_guaranteeProperRendering_forPresentedView() throws {
    // Given
    let containerWindow = UIWindow(frame: UIScreen.main.bounds)
    let sut = MyViewController(
        animationsEnabled: false // <- this is key. I use this flag in places such as present(newViewController, animated: animationsEnabled)
    )
    containerWindow.rootViewController = sut
    containerWindow.makeKeyAndVisible()

    // When
    sut.loadViewIfNeeded()
    sut.methodThatPresentANewController() 

    // Verify
    let presentedDropDown = try XCTUnwrap(sut.presentedViewController)
    assertSnapshot(viewController: presentedDropDown) // <- Using SnapshotTesting lib from @pointfree folks 
}
```

Worked like a charm
