### ISSUE TITLE
Missing ResourceRules.plist file?

### ISSUE THREAD

**Issue by MichaelHackett** [specta/specta#113]
The Rake build fails in the iOS Framework step because the `codesign` command is referencing a file, `ResourceRules.plist`, which does not appear to exist.

````
=== CODESIGN iOS FRAMEWORK ===
Running /usr/bin/codesign --force --sign 'iPhone Developer' --resource-rules='Specta/build/Release-ios-universal/Specta.framework'/ResourceRules.plist 'Specta/build/Release-ios-universal/Specta.framework'...
Specta/build/Release-ios-universal/Specta.framework/ResourceRules.plist: cannot read resources
rake aborted!
** BUILD FAILED **
````

Running Xcode 6.1, fresh clone of Specta master branch.

**Comment by orta** [comment]
PR merged. Though @tonyarnold's point about removal is probably legit.

**Comment by fuckasaurus** [comment]
probably late to the party but if jailbroken on later versions than 6 (muat still be 32 bit) any app that requires it if its been cracked and the date matches the rest of the files in the app then the resourcerules.plist will work, i have tested this on ramp champ version 1.1.2
