### ISSUE TITLE
Support for Objective-c++ 

### ISSUE THREAD

**Issue by hfossli** [specta/specta#115]
Some parts of my code have c++ in the objective-c header files. When I write unit tests for these classes my unit tests should have the `.mm` extension instead of `.m`. When I do that even simple specs fail.

```
#define EXP_SHORTHAND
#import "Expecta.h"
#import "Specta.h"

SpecBegin(Thing)

describe(@"Thing", ^{

    beforeEach(^{
        BOOL myBoolIsMine = YES;
        expect(myBoolIsMine).to.equal(TRUE);
    });
    
});

SpecEnd
```

**Comment by orta** [comment]
I think https://github.com/specta/specta/pull/120 has fixed this.

**Comment by hfossli** [comment]
Cool
