### ISSUE TITLE
0.30 - BAD_ACCESS in runGlobalBeforeEachHooks against "GAITrackerModel"

### ISSUE THREAD

**Issue by alexmalek** [specta/specta#116]
Hey, we're seeing a crash in runGlobalBeforeEachHooks.ClassesWithClassMethod - for some reason it's unhappy doing a class_getClassMethod against GAITrackerModel (part of Google Analytics). Racking my brain trying to understand what the issue is. Any thoughts? 

![screen shot 2014-11-27 at 1 52 19 pm](https://cloud.githubusercontent.com/assets/150215/5222004/532fde04-763e-11e4-9aa7-44e7c016a22a.png)

**Comment by foulkesjohn** [comment]
We are having this issue and need to use 3.0.10 for GA, we currently have a fork which has a check for GAITrackerModel but we ideally need something more permanent.

**Comment by orta** [comment]
Fixed in #131

( You can add support in your project to make it skip any specific class )
