### ISSUE TITLE
Specta with multithreaded tests

### ISSUE THREAD

**Issue by J-Rojas** [specta/specta#123]
First off, thank you to the maintainers of this library. It has made writing tests in Objective-C less of a chore.

I have many asynchronous operations that I need to test. To help with this, I use a promise library (RXPromise in particular) to execute consecutive blocks after certain conditions are fulfilled. The promises run on their own dispatch queue and in their own background thread.

The problem that I'm experiencing is that when I run expectations within the promise blocks, the ones that fail do not cause Specta to register a failed test. The expectations do print out their errors, but when the test completes, the calls to [XCTestCase recordFailureWithDescription:inFile:atLine:expected] are never executed.

Digging through the Specta code, I found the problem is that when running on a different thread other than the main thread, the current test spec that is stored in a thread local dictionary is nil, causing the expectations to never record their failures. See the excerpts below:

SpectaUtility.h

    #define SPTCurrentTestSuite [[NSThread currentThread] threadDictionary][spt_kCurrentTestSuiteKey]
    #define SPTCurrentSpec  [[NSThread currentThread] threadDictionary][spt_kCurrentSpecKey]

SPTSpec.m:

    - (void)recordFailureWithDescription:(NSString *)description inFile:(NSString *)filename atLine:(NSUInteger)lineNumber expected:(BOOL)expected {
        SPTSpec *currentSpec = SPTCurrentSpec;
        [currentSpec.spt_run recordFailureWithDescription:description inFile:filename atLine:lineNumber expected:expected];
    }

Redefining the macros above to the code below solves my problem; I am able to have failed expectations in another thread cause the current test to fail:

    #define SPTCurrentTestSuite [[NSThread mainThread] threadDictionary][spt_kCurrentTestSuiteKey]
    #define SPTCurrentSpec  [[NSThread mainThread] threadDictionary][spt_kCurrentSpecKey]

I'm thinking that Specta's design of using thread local data is important, possibly for parallelizing tests. So is there a recommended approach to solving this problem using the current code base?

Thanks for the help.

**Comment by J-Rojas** [comment]
Thanks for looking into this. I've tried the recent changes in master made by @neonichu, but they did not work for me.

The problem I'm seeing as I described above is related to SPTSpec.m, line 202. 
The current spec is nil here and the failures are not recorded.

**Comment by neonichu** [comment]
This is weird, because with my changes, `-recordFailureWithDescription:inFile:atLine:expected:` should only ever be called from the main thread. Are you able to share a reproducible case of this maybe?

**Comment by J-Rojas** [comment]
Yes, I was able to find a reproducible case. Your test does work for me (it fails as expected on the background thread). However I'm using Expecta, and those expectations fail.

Here's the case that is failing:

        it(@"assert on background queue", ^{
            waitUntil(^(DoneCallback done) {
                dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                    expect(@0).to.beTruthy();
                    done();
                });
            });
        });

**Comment by orta** [comment]
Expecta will need a similar PR I think.

**Comment by orta** [comment]
Yep: https://github.com/specta/expecta/blob/master/Expecta/ExpectaSupport.m#L161-L175

Would love a PR

**Comment by J-Rojas** [comment]
I tried modifying the code in Expecta as you pointed out (changing currentThread -> mainThread) but this did not work for me.

I instead applied the patch to Specta and my use cases started to work.

https://github.com/specta/specta/pull/134
