### ISSUE TITLE
When using a pending() behavior, beforeAll is called again unexpectedly.

### ISSUE THREAD

**Issue by J-Rojas** [specta/specta#124]
In 0.3.0-beta, I've observed this behavior fail when using a pending behavior test:

    SpecBegin(SpectaTests)

    __block int callOnce = 0;

    beforeAll(^{
        //this is called more than once when pending() is used!
        callOnce++;
        expect(callOnce).equal(1);
    });

    beforeEach(^{
        //this is called after each behavior
    });

    describe(@"Specta", ^{

        pending(@"should call this pending behavior test.", ^{

        });

        it(@"should call this behavior test.", ^{

        });

    });

    SpecEnd

BeforeAll should only be called once regardless of the use of pending/it behavior blocks.

**Comment by orta** [comment]
I think this makes sense, would love to see a PR :+1:

**Comment by dbarden** [comment]
I'm getting that afterAll is being called twice, with the following test:

```
#import "TestHelper.h"

static int
beforeAllRan
, afterAllRan
;

SpecBegin(_PendingSpecTest5)

describe(@"group", ^{
    beforeAll(^{
        beforeAllRan ++;
    });

    it(@"example 1", ^{ });

    it(@"example 2", ^{ });

    pending(@"testing");

    afterAll(^{
        afterAllRan ++;
    });
});

SpecEnd

@interface PendingSpecTest5 : XCTestCase; @end
@implementation PendingSpecTest5

- (void)testPendingAndItMixed {
    beforeAllRan = afterAllRan = 0;

    RunSpec(_PendingSpecTest5Spec);

    assertEqual(beforeAllRan, 1);
    assertEqual(afterAllRan, 1);
}

@end
```

I'll try to find some time to dig on the internals and see what's causing this.
Unless somebody is faster.
