### ISSUE TITLE
CI is broken on master

### ISSUE THREAD

**Issue by orta** [specta/specta#127]
Looks like its around sequence support. https://travis-ci.org/specta/specta/builds/50258272

It seems to be that [the helper functions](https://github.com/specta/specta/blob/master/Specta/SpectaTests/SequenceTest.m#L10-L16) are not being ran at all.

**Comment by paweldudek** [comment]
Looks like this broke after https://github.com/specta/specta/pull/119 was pulled in, at least according to history: https://travis-ci.org/specta/specta/builds

**Comment by paweldudek** [comment]
That's probably it as the pulled in change is closely related to global before/after each logic.

**Comment by orta** [comment]
Makes sense, digging right now :+1:

**Comment by orta** [comment]
Yeah, that's definitely it.

**Comment by orta** [comment]
Day one making changes and something already needs to be reverted :dancers:

**Comment by paweldudek** [comment]
Yeah, wish there was a "run against current master" button for Travis CI.
