### ISSUE TITLE
Swift Support

### ISSUE THREAD

**Issue by orta** [specta/specta#130]
Initial implementation can be found in this commit: https://github.com/specta/specta/commit/596f0a19195ead8c7aa6b905457f13dca9b24caf

**Comment by orta** [comment]
I think the tradeoff of 

>  All Obj-C global functions are now prefixed with `spt_`. This is to provide unprefixed versions functions of the same name for Swift. It is recommended to add shorthands to your Obj-C test helper header. The  rest of this document assumes that shorthands are used.

Is quite serious.

**Comment by tonyarnold** [comment]
Are the un-prefixed variants of the Objective-C functions still the default? Or does this mean that the prefix _has to be used_? That would be an unacceptable compromise, IMO.

**Comment by petejkim** [comment]
I think we can get around the issue by creating a separate framework (e.g. Specta-Swift) that uses the objc Specta framework.

**Comment by orta** [comment]
> I think we can get around the issue by creating a separate framework (e.g. Specta-Swift) that uses the objc Specta framework.

Think this is a great idea. `Suspecta`

**Comment by orta** [comment]
OK, think this is also fine to be closed, I think encouraging Quick/Nimble as a great option for Swift support is probably the best call.
