### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by paweldudek** [specta/specta#139]
A few fixes/changes made it into master and it'd be cool to have them available as new release:

https://github.com/specta/specta/pull/136
https://github.com/specta/specta/pull/135
https://github.com/specta/specta/pull/134
https://github.com/specta/specta/pull/133
https://github.com/specta/specta/pull/131

Any chance someone could tag & release a new version on Cocoapods? :wink:

**Comment by orta** [comment]
Done!
