### ISSUE TITLE
Add Carthage support to README

### ISSUE THREAD

**Issue by dbarden** [specta/specta#146]
Did anybody already tried Specta using Carthage? Is it supported? 

If no one did it yet, I'll just create a sample project to test and add the instructions to the README.

**Comment by tonyarnold** [comment]
I ensured Expecta works with Carthage, but I didn't try Specta. Chances are that if it's a shared scheme it will just work out of the box.

**Comment by dbarden** [comment]
Yeap, it works. Just migrated a project to use Carthage.

Had some problems due to not adding the copy frameworks steps. But RTFM helps quite a lot in these situations.
