### ISSUE TITLE
Class + (void)initialize called multiple times?

### ISSUE THREAD

**Issue by valerius** [specta/specta#150]
Not sure if this issue is specific to your API or testing in general, but while trying to write a test for some of my classes, which used +initialize() to register themselves in a singleton, I notice that the initialize function is called multiple times. I can say however, it works fine for the standard application, or the Cedar test suite which runs test as the application as apposed to a "Test" target/scheme, so I'm guessing that may be the issue. Not sure. Anyways, heres an oversimplified example:

```objective-c

describe(@"sample jobs schould schedule", ^{
    beforeEach(^{
         [NLManager resetDatabase];  //cycles through all registered objects and removes associated data
    });

    it(@"save records", ^{
       NLRecord *record = [NLRecord new];  //NLRecord and subclasses registers itself with manager upon initialize, but manager appears to be reset initialized multiple times even though its a singleton
       [record save];
       expect([[NLRecord allRecords] count]).to.equal(1); // fail, because [NLManager resetDAtabase] don't have any registered objects to cycle through and remove all records of each registered type. Because once set, the manager is initialized again.
    });

});
```
Any help would be greatly appreciated, even though it may be testing general instead of Specta specific. However, I know the code works, just wanted to write some test before publishing the CocoaPod.

**Comment by modocache** [comment]
Is `NLRecord` part of your application target, your test target, or both? If it's included in both your application and test target, then it's actually two different classes, and you may see both of them registered. Just a theory! :bulb:

**Comment by valerius** [comment]
Hey modocache! Thanks so much for the theory, that turned out to be substantively the case, with slightly different minutia involved.  Namely, I had to change my testing bundles "Host Application" to None, and then add the sample classes to my target manually. A greater detail of the answer is here should someone be interested:

https://github.com/AliSoftware/OHHTTPStubs/wiki/A-tricky-case-with-Application-Tests

My initial thoughts rested upon the fact that some testing/scripting frameworks may reload the classes to nix any dynamic/meta methods added and other misc reasons, and wondered if that could be possible here. But apparently, that was not the case. Anyways, the framework rocks and really appreciate you getting me onto the right track. Happy coding!

**Comment by modocache** [comment]
@valerius Great resource, thanks for the link! :+1:
