### ISSUE TITLE
When I include Specta.framework to "Link binary with Libraries" I get "Test Failed"

### ISSUE THREAD

**Issue by Goles** [specta/specta#151]
Hey there,

I'm working on a Library (it's not an app) and I built Specta with Carthage. After which I followed the instructions to add Specta to my Test Target (basically put the Framewrok in the Link Binary with Libraries build phase).

I tried to run my tests, my Library builds, but I get a "Test Failed" Xcode alert.

Just to try, I removed _all_ the tests from my project, and then hit `cmd+U` to run -no tests-. I get the same "Test Failed" alert.

If I remove the Specta Framework from the Link Binary with Libraries build phase and then hit `cmd+U` I get a "Test Succeeded" alert (note that I even removed all my tests from this project).

Note: Using Xcode 6.3 (6D570) and running the tests from a workspace.

I noticed the following in the debugger log

```bash
2015-04-15 16:02:33.365 xctest[84115:6211684] The test bundle at /Users/username/Library/Developer/Xcode/DerivedData/Lol-eczhlvkltknvoucjnbttqmzhfynq/Build/Products/Debug-iphonesimulator/LolTests.xctest could not be loaded because an unanticipated error occurred.
2015-04-15 16:02:33.366 xctest[84115:6211684] Detailed error information: Error Domain=NSCocoaErrorDomain Code=3587 "The bundle “LolTests” couldn’t be loaded because it is damaged or missing necessary resources." (dlopen_preflight(/Users/username/Library/Developer/Xcode/DerivedData/Lol-eczhlvkltknvoucjnbttqmzhfynq/Build/Products/Debug-iphonesimulator/LolTests.xctest/LolTests): Library not loaded: @rpath/Specta.framework/Specta
  Referenced from: /Users/username/Library/Developer/Xcode/DerivedData/Lol-eczhlvkltknvoucjnbttqmzhfynq/Build/Products/Debug-iphonesimulator/LolTests.xctest/LolTests
  Reason: image not found) UserInfo=0x7fb8b36084a0 {NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/username/Library/Developer/Xcode/DerivedData/Lol-eczhlvkltknvoucjnbttqmzhfynq/Build/Products/Debug-iphonesimulator/LolTests.xctest/LolTests, NSDebugDescription=dlopen_preflight(/Users/username/Library/Developer/Xcode/DerivedData/Lol-eczhlvkltknvoucjnbttqmzhfynq/Build/Products/Debug-iphonesimulator/LolTests.xctest/LolTests): Library not loaded: @rpath/Specta.framework/Specta
  Referenced from: /Users/username/Library/Developer/Xcode/DerivedData/Lol-eczhlvkltknvoucjnbttqmzhfynq/Build/Products/Debug-iphonesimulator/LolTests.xctest/LolTests
  Reason: image not found, NSBundlePath=/Users/username/Library/Developer/Xcode/DerivedData/Lol-eczhlvkltknvoucjnbttqmzhfynq/Build/Products/Debug-iphonesimulator/LolTests.xctest, NSLocalizedDescription=The bundle “LolTests” couldn’t be loaded because it is damaged or missing necessary resources.}


*** Test session exited(1) without checking in. If you believe this error represents a bug, please attach the log file at /var/folders/3j/gfn5fzjx7cl8qx40v87hjqv00000gp/T/com.apple.dt.XCTest-status/Session-2015-04-15_16:02:32-FoxsoD.log
```

**Comment by dbarden** [comment]
Hi @Goles,

is it an iOS project? I had this issue, but it got solved after adding the _Run Script Phase_ to the build process (step 4 on the integration instructions)

**Comment by Goles** [comment]
Hey guys,

I was able to get Specta to work, the problem was that apparently my project was missing the correct `Runpath Search Paths` in the Build Settings.

It's a pretty old project, so maybe those were not added by Xcode in the past?

Anyway, here's how they look now:

```bash
$(inherited)
@executable_path/Frameworks
@loader_path/Frameworks
```
![screen shot 2015-04-16 at 11 15 34 am](https://cloud.githubusercontent.com/assets/181342/7188103/34d01104-e42a-11e4-8d72-5ff4993b6d63.png)
