### ISSUE TITLE
NO CHANGELOG entry for 1.0.0

### ISSUE THREAD

**Issue by mickeyreiss** [specta/specta#155]
Great release!

I noticed that the CHANGELOG doesn't include an entry for 1.0.0. Is this intentional? The info would definitely be convenient.

**Comment by mokagio** [comment]
I thiught that as well, but if you look at the commits nothing has been actually changed between the last dev version and 1.0, just newlines and Coveralls integration.

**Comment by mickeyreiss** [comment]
@mokagio I see. I think a note in the CHANGELOG might be helpful for folks less involved the project day to day. I wrote up [a suggestion](https://github.com/specta/specta/pull/156) for what the 1.0.0 notes might look like. Hope it's helpful!
