### ISSUE TITLE
Exceptions don't fail a test "unexpectedly"

### ISSUE THREAD

**Issue by mfclarke** [specta/specta#158]
Hi. It looks like if there's an exception while running a test it isn't reported correctly. The console says `Executed 8 tests, with 1 failures (0 unexpected)`. Because the failure is apparently expected, Xcode doesn't mark the test as failed and my unit tests are apparently all passing.

Correct me if I'm wrong, but a crash should fail a test unexpectedly.

**Comment by orta** [comment]
There are tests around unexpected Exceptions, in [UnexpectedExceptionTest.m](https://github.com/specta/specta/blob/master/Specta/SpectaTests/UnexpectedExceptionTest.m) that pass. 

Do you have some reproducible code?

**Comment by mfclarke** [comment]
This issue actually doesn't have anything to do with unexpected vs expected. Apologies. I will create a new issue with the real problem.
