### ISSUE TITLE
Run Individual Spec instead of all of them

### ISSUE THREAD

**Issue by KattMingMing** [specta/specta#160]
I'm having trouble running one spec. When I press the "play" button that is embedded above the line numbers Specta does not run one Spec rather it runs all of them. I saw https://github.com/specta/specta/issues/45, but using fit or fdescribe does not help with this. Is there a way to run tests individually or was this how they were run individually and it doesn't work anymore?

**Comment by orta** [comment]
Hrm, can you verify that the test are actually being ran? Xcode still tells you the names of the tests I believe, but they're just not ran.

**Comment by KattMingMing** [comment]
@orta they are all running. Tested with failing tests and also passing tests to confirm. For clarification, a file that contains multiple Spec's runs all of them and it also runs every Spec in other files.

**Comment by KattMingMing** [comment]
So I think I figured out what is happening and you are correct. It seemed strange to me that the breakpoints in the other spec would be hit even though they are not running the tests. So you were correct. Thanks for the quick reply.
