### ISSUE TITLE
Focused tests should be called out in the console log

### ISSUE THREAD

**Issue by eremzeit** [specta/specta#166]
![image](https://cloud.githubusercontent.com/assets/1264533/8245233/59ab9236-15e0-11e5-9d23-7213afe1462c.png)

I have about 80 tests that I've written in Specta and have for a while been regularly using with no issue, but just now as I was developing I must have changed something because now none of my tests will run.  The console output reports that each test has run (mentioning each individually), and if I can hit breakpoints in the `it` and `describe` statements and see that they are getting run.  However, none of the code in each of the test blocks appears to be executing.  What did I do?  I'm running Specta 0.5.

![image](https://cloud.githubusercontent.com/assets/1264533/8245227/455c8d3a-15e0-11e5-8f98-5d30ab3c59d3.png)

**Comment by eremzeit** [comment]
Oh, whoops.  I had a typo that added an `f` to `describe` so it was skipping all the blocks.  PEBKAC.

Though, on the other hand, it might be useful for the console logs actually reflect what is happening.  Ie. if only one test is being run because of an `f` maybe it should just tell you that.

**Comment by robb** [comment]
That seems like a good idea.

**Comment by jmoody** [comment]
+1

Someone on my team committed an `f` tag which went unnoticed for a month.  This is a very dangerous feature of Specta.

**Comment by blackivory86** [comment]
+1

'Someone' on my team did that as well.
Guessed right - it was me. Again, and again, and ...

**Comment by webventil** [comment]
+1

**Comment by johannes82** [comment]
+1

**Comment by orta** [comment]
A PR is far more useful than a +1, please don't do them.

**Comment by idellwig** [comment]
+1

**Comment by orta** [comment]
Seriously?
