### ISSUE TITLE
how about variables?

### ISSUE THREAD

**Issue by pvinis** [specta/specta#170]
With XCTest, i could add some variables inside the @implementation block, and i could initialize them in the setUp.

can i have variables with specta?

**Comment by robb** [comment]
Sure

```objc
SpecBegin(Thing)

__block id foo;

beforeEach({
    foo = [Foo new];
});

SpecEnd
```

**Comment by pvinis** [comment]
thanks

On 9 Jul 2015 at 14:45:30, Robert Böhnke (notifications@github.com) wrote:

Sure

SpecBegin(Thing)

__block id foo;

beforeEach({
    foo = [Foo new];
});

SpecEnd
—
Reply to this email directly or view it on GitHub.

-- 
Pavlos Vinieratos

**Comment by pvinis** [comment]
is it better to add them after SpecBegin with __block, or to add them before SpecBegin without __block?

**Comment by robb** [comment]
I think you'd have to make the variable `static` if you wanted to use it outside of `SpecBegin`. I'd generally put everything after `SpecBegin`.

Note that you only need to use `__block` when you want to assign a value in e.g. `beforeEach`, which I believe is generally a good idea to make sure there is no shared state between tests.

**Comment by orta** [comment]
@pvinis if you want to look at a collection of Specta/Expecta tests, you can check out: https://github.com/artsy/eigen/tree/master/Artsy_Tests

**Comment by pvinis** [comment]
@robb  @orta thanks!
