### ISSUE TITLE
Fix warnings in Xcode 7 GM Seed

### ISSUE THREAD

**Issue by iosdev-republicofapps** [specta/specta#177]
Hi,

Love Specta, awesome tool!

I would like to disable build warnings when compiling Specta both as a standalone and as a Cocoapod.  In particular:
```
In file included from /Users/joel/src/specta/Specta/Specta/XCTestCase+Specta.m:7:
/Users/joel/src/specta/Specta/Specta/XCTest+Private.h:24:11: warning: duplicate protocol definition of 'XCTestObservation' is ignored
@protocol XCTestObservation <NSObject>
          ^
In module 'XCTest' imported from /Users/joel/src/specta/Specta/Specta/XCTestCase+Specta.h:1:
/Applications/Xcode 7 GM Seed.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCTestObservation.h:28:11: note: previous definition is here
@protocol XCTestObservation <NSObject>
          ^
1 warning generated.
```

I tried all the `pragma clang diagnostic` tricks I could think of and Googled for some time and couldn't find a solution.  I think it's important to have warning-free builds, even for test targets, so any idea how we can fix this?

The code in question is a duplicate definition of `XCTestObservation`:
```
@protocol XCTestObservation <NSObject>
@end
```
Just curious: why are you redefining it and why as empty?  Apple already defined it.

Is there a way to do this without generating this distracting warning?

Thanks and have a great weekend!

**Comment by orta** [comment]
@modocache any ideas?

**Comment by rad3ks** [comment]
I made PR #182 that resolves the issue. It currently doesn't pass CI due to older Xcode on travis, where `XCTestObservation` is not defined by `XCTest`, but you can point directly to this commit/branch in your Podfile (if you're using cocoapods to integrate specta with your project).

```

**Comment by orta** [comment]
This is fixed in master :+1:
