### ISSUE TITLE
Specta skipping through tests in sample Xcode 7 project

### ISSUE THREAD

**Issue by Goles** [specta/specta#183]
Hey there,

Specta seems to be skipping through all the tests in this [Sample Project](https://dl.dropboxusercontent.com/u/1149996/SpectaTest.zip), running under `Version 7.0 (7A218)`

<img width="417" alt="ss" src="https://cloud.githubusercontent.com/assets/181342/9951751/a28768a4-5d7f-11e5-8c56-ab9f70e9b444.png">

Don't really know what's going on... setting breakpoints seems to hit the `it` line of the test but doesn't go in.

The project was built with carthage, and it's super small, so checking it should not be hard.

**Comment by rbaumbach** [comment]
Is it possible to write specs with an 'it' inside of an 'it?'  I was always under the impression that the it is the final "block" of code that could be nested in multiple 'describes' and 'contexts.'

**Comment by orta** [comment]
Yeah, this is a usage problem, `describe`s  should be used for grouping, and `it` is used for the tests. In implementation terms an `it` represents an XCTestCase, and they cannot be built inside each other.
