### ISSUE TITLE
Specta does not build on XCode7

### ISSUE THREAD

**Issue by adamkaplan** [specta/specta#185]
The underlying issue is resolved already by #178. The commit is un-released, so in effect Specta is still broken for most Carthage users.  I have made this ticket to track the issue.

Until then, Carthage users need/should add this line to their `Carthage.private` files.
`github "specta/specta" "3d127e6a14e9f4759fbde50272481260775b193b"`

I have filed this ticket so that we can watch the issue and know when it's safe to move Carthage back to the pinned-major version (or, ~> 1).

**Comment by melote** [comment]
+1

**Comment by orta** [comment]
New version deployed.
![screen shot 2015-09-22 at 07 56 20](https://cloud.githubusercontent.com/assets/49038/10012383/70028d18-60ff-11e5-8266-f02fa63bbdc5.png)

**Comment by orta** [comment]
also, @melote - please don't go around +1ing a bunch of things, as someone with enough github email a bunch of +1s only make it harder to decide what I want to work on.

**Comment by adamkaplan** [comment]
Thanks @orta!
