### ISSUE TITLE
"Questionable API usage" error when using XCTestExpectation

### ISSUE THREAD

**Issue by Goles** [specta/specta#188]
I'm trying to use `XCTestExpectation` with Specta in the following way

```objective-c
#import <Specta/Specta.h>

SpecBegin(ATest)
describe(@"A Spec", ^{
	it(@"Is a test", ^{
		XCTestExpectation *exp = [self expectationWithDescription:@"An expectation"];
		[exp fulfill];
		[self waitForExpectationsWithTimeout:0.5 handler:nil];
	});
});
SpecEnd
```

That leads to the following console errors.

```
Questionable API usage: creating XCTestExpectation for test case -[ATestSpec (null)] which is not the currently running test case -[ATestSpec test_A_Spec__Is_a_test]

2015-09-24 17:09:29.608 XctoolSample[61649:1781293] Questionable API usage: called -[XCTestExpectation fulfill] for An expectation after the test case in which the expectation was created is no longer running. 

Created in test -[ATestSpec (null)], current test is -[ATestSpec test_A_Spec__Is_a_test]
```

I created a [sample project](https://dl.dropboxusercontent.com/u/1149996/SpectaSample2.zip) to expose the issue (still present in Specta `1.0.4`).

It does also look a lot like what these guys are seeing in this [ticket](https://github.com/Quick/Quick/issues/330) on in the Quick project.

**Comment by orta** [comment]
Probably best to use specta's waitUntil:

```
  it(@"should do some stuff asynchronously", ^{
    waitUntil(^(DoneCallback done) {
      // Async example blocks need to invoke done() callback.
      done();
    });
  });
```

Given that we don't expose XCTest anywhere else.

**Comment by Goles** [comment]
Didn't know about that one, will give it a shot.

**Comment by orta** [comment]
Calling as done, we've only used `waitUntil` in multiple codebases and been happy. Would be happy to take PRs on allowing the usage of XCTExpectations though.

**Comment by restjohn** [comment]
Is there a pattern for using `waitUntil` that repeatedly checks whether a condition has been satisfied as `waitForExpectionsWithTimeout:handler:` does?  For a while I had assumed that was the way `waitUntil` worked, but I had async tests failing and finally looked at the code behind `waitUntil` and realized it was only calling the passed block once.  Then I switched to the [XCTestCase waitForExpectationsWithTimeout:handler:] async facility which gave me the repeated condition checking behavior, but also the error message this issue describes.  So what is the best practice for using `waitUntil` in a similar manner?

**Comment by orta** [comment]
That's handled by matcher libraries normally, https://github.com/specta/expecta#asynchronous-testing

**Comment by restjohn** [comment]
Ah, thanks very much.  I don't know how I missed that all this time.
