### ISSUE TITLE
Carthage Binaries

### ISSUE THREAD

**Issue by Autoc0diq** [specta/specta#192]
Would it be possible to add binaries to your releases? This would speed up our build time. Thanks!

**Comment by orta** [comment]
This is a duplicate of #187

**Comment by robb** [comment]
FWIW, I'd be looking into committing frameworks with git lfs now.

**Comment by Autoc0diq** [comment]
Is it supported by Carthage?

-s

**Comment by robb** [comment]
Checking in `Carthage/Build` should do the trick I reckon
