### ISSUE TITLE
waitUntil hangs when using Specta in XCTest UI Test target

### ISSUE THREAD

**Issue by blackivory86** [specta/specta#193]
I'm trying to use Specta and Expecta in the new XCode 7 UI Tests.
Some of my tests use `waitUntil` to wait for asynchronous actions to finish. However `waitUntil` never calls it's block and therefore never calls the `DoneCallback`

I don't have any problems with my default unit-test target but it's happening with my UITest target.

**Comment by orta** [comment]
You might be the first to look into this, any chance you can dig in and get us a PR?

**Comment by blackivory86** [comment]
I'm currently setting up a bare test-case without my other dependencies.
Not sure how much time I can put into this...

**Comment by blackivory86** [comment]
- Created a single-view application
- added UI test target
- added specta to UI test-target
Still not working

```Objective-C
dispatch_async(dispatch_get_main_queue(), ^{
    block(^{
      OSAtomicOr32Barrier(1, &complete);
    });
  });
```
Seems to never execute the block

**Comment by blackivory86** [comment]
Seems to be a general problem with dispatching on the main queue. This does not work even with a test project without Specta

**Comment by orta** [comment]
I don't know much about how UI tests work, do they have constraints around threading? 

It might be worth seeing if an XCTestExpectation works (outside of Specta) in UITesting

**Comment by blackivory86** [comment]
Everything is working fine with Xcode 7.1

**Comment by orta** [comment]
Hah, thanks for digging in @blackivory86 !
