### ISSUE TITLE
Specta getting stuck when trying to dispatch_sync in the main queue

### ISSUE THREAD

**Issue by Goles** [specta/specta#198]
I'm trying to do something like

``` objective-c
    dispatch_sync(dispatch_get_main_queue(), ^{
       ...
       ...
       ...
    });
```

Specta seems to get stuck on this, I wrote a [sample project](https://dl.dropboxusercontent.com/u/1149996/SpectaMainThreadTest.zip) to demonstrate the behavior.

**Comment by FerencYAO** [comment]
i think should dispatch_async

2015年12月16日星期三，Nicolas Goles <notifications@github.com> 写道：

**Comment by Goles** [comment]
@FerencYAO When not running this code in specta, everything is fine tbh... am I missing something?

**Comment by pk** [comment]
I've been experiencing the same behaviour for some time. If the code under the test uses `dispatch_sync` it hangs tests, one way around it would be to use `dispatch_async` in combination with something like

    waitUntil(^(DoneCallback done) .{
        [obj takesLongTimeWithCompletion:^{ done(); }];
    });

**Comment by Goles** [comment]
@pk The `dispatch_sync` lies in a method of a Class that I'm testing, and has it's own reasons for being sync, so for me, there's sadly no way around it :disappointed:
