### ISSUE TITLE
Add watchos support

### ISSUE THREAD

**Issue by lolgear** [specta/specta#204]
Any plans about it?

**Comment by orta** [comment]
No plans for it, it's been a pretty niche platform. Would definitely merge a PR adding it to the Podspec after you've tested it.

**Comment by lolgear** [comment]
Assign this issue to me, please, I am going to merge PR as soon as possible

**Comment by orta** [comment]
:+1:  can't assign people not in the org, but consider it yours

**Comment by orta** [comment]
Gonna call this one for now, you're welcome to re-open via a PR.
