### ISSUE TITLE
Hierarchical test results

### ISSUE THREAD

**Issue by aspcartman** [specta/specta#205]
The Kiwi output:
<img width="330" alt="screen shot 2016-03-25 at 12 11 03 pm" src="https://cloud.githubusercontent.com/assets/844194/14041530/40f5107c-f28b-11e5-9ee9-3581914f0aa4.png">

The Specta output:
<img width="344" alt="screen shot 2016-03-25 at 12 11 12 pm" src="https://cloud.githubusercontent.com/assets/844194/14041535/488d06b4-f28b-11e5-9555-a4a7abd35410.png">

Reading the #99 didn't help. What's the difference? How to get rid of those underscores and get the actual hierarchy as Kiwi does?

**Comment by orta** [comment]
AppCode has special support for Kiwi, but not for Specta alas.
