### ISSUE TITLE
WaitUntil and WaitUntilTimeOut leads to EXC_BAD_ACCESSS

### ISSUE THREAD

**Issue by dtaitz** [specta/specta#210]
Hello,

I am using Specta (1.0.5) and Expecta (1.0.5). I use the BFTask library for asynchronous operations. 

Most of the times I run my test suite, I end up getting EXC_BAD_ACCESS from running the below code:

       waitUntilTimeout(3.0, ^(DoneCallback done) {
                
                [[sut refreshUser:mockCurrentUser userDefaults:mockDefaults permissionsManager:mockPermissionsManger] continueWithExecutor:[BFExecutor mainThreadExecutor] withBlock:^id(BFTask * task) {
                    
                    
                    [verifyCount(mockCurrentUser, never()) setIsProxyUser:YES];
                    [verifyCount(mockCurrentUser, never()) saveInBackground];
                    
                    done();
                    return task;
                }];
            });

It seems to break on the implementation on WaitUntilTimeOut at the following line:

    while (!complete && [timeoutDate timeIntervalSinceNow] > 0) {
       [[NSRunLoop currentRunLoop] runUntilDate:[NSDate dateWithTimeIntervalSinceNow:0.01]];
    }

It is all running on the main thread, so I would appreciate any help in figuring out this issue as I cannot run my test suite without solving this.

David

**Comment by orta** [comment]
I'm afraid I don't really know too much about how `BFTask` works, and from the looks of it, neither does any of the other contributors. It might be more prudent to ask if there's anything that BFTask does that might have issues around running inside a separate runloop.
