### ISSUE TITLE
It would be nice if specta had an option to reset the app after each test file completes

### ISSUE THREAD

**Issue by mbrooks** [specta/specta#212]
One of things I've noticed about testing with iOS is that the app is loaded only once and the same instance is used for each test. Maybe I am just doing things wrong, but it's very easy to get test leakage from one test to another if you forget to tear down your tests correctly. 

For example, if you add an observer to test for a notification and forget to tear it down, and another test tests something that also fires the same notification, the first notification will still fire and if the expects fail, then it will say that there was an issue in the current running test, even though the error was in the first one.

Of course, the real answer here is just, write your tests correctly and this won't happen, but after hours of debugging these types of events, you just really wish the tool would help you out here for your poor coding skills ;)

Would it be possible to add an option to specta that would reset the app after each test file completes? This, in theory, would clear out any undesirable state left over from any other tests. I.e. remove observers, etc

**Comment by orta** [comment]
Not really, Xcode opens the application and then tells the test runner that it should start and eventually to close. 

The other side of this, is that loading your app up from scratch takes ~2-3 seconds, I don't think anyone wants to wait that long between each test. _maybe_ between each test suite, but still, it's outside of Specta/Kiwis scope - you'd need to replace the test runner, or have an Xcode plugin to pull it off I'm afraid.
