### ISSUE TITLE
Specta + lcov Code Coverage Addition

### ISSUE THREAD

**Issue by thiagolioy** [specta/specta#64]
Hi ,
i was trying to get code coverage on my ios project using specta , i had already managed to do that using xctest following this solution (http://stackoverflow.com/questions/19136767/generate-gcda-files-with-xcode5-ios7-simulator-and-xctest )

After struggle a little bit i've realized that if i override the XCTestLog_stopObserving method of XCTestLog+Specta.m , and add these 2 extra lines(Bold).

- (void)XCTestLog_stopObserving {
  if ([self spt_shouldProxyToSPTReporter]) {
     [[SPTReporter sharedReporter] stopObserving];
     
      UIApplication* application = [UIApplication sharedApplication];
      [application.delegate applicationWillTerminate:application];
     
  } else {
     [self XCTestLog_stopObserving];
    usleep(100000);
  }
}
and inside my AppDelegate's willTerminate method , i've added this lines(From stackoverflow solution) :

- (void)applicationWillTerminate:(UIApplication *)application
{
#ifdef DEBUG
    extern void __gcov_flush(void);
    __gcov_flush();
#endif
} 
With this steps done , i could manage to generate the .gcda that lcov/gcovr need to create the code coverage.

This solution does not require to create a GcovTestObserver as the stackoverflow thread suggest  nor to override the load method on appDelegate if in debug mode .

Can i use this approach ?  Does it make sense to have this extra lines inside this method ?

I've created a shell script to override this method inside the pods dir adding this 2 lines , so i could use it as pre build step with my ci server after a pod install .
Right now , im using it as a workaround solution . Can i hope to see this workaround done inside specta , or another solution to answer the problem of .gcda files not being generated.

Thanks for your time , Best regards

**Comment by dbarden** [comment]
Is this issue still valid?

We're using code coverage and didn't need to do any modification on Specta code.

I'd suggest to close it, if it doesn't make sense anymore.

**Comment by orta** [comment]
Works for me 👍 - less is less.
