### ISSUE TITLE
Shared behavior doesn't fail when missing

### ISSUE THREAD

**Issue by benjamincox** [specta/specta#68]
I took the example from the Github project page, but removed the whole SharedExamplesBegin -> SharedExamplesEnd section:

    #import "Specta.h"
    
    SpecBegin(Thing)
    
    describe(@"Thing", ^{
      sharedExamplesFor(@"another shared behavior", ^(NSDictionary *data) {
        // Locally defined shared examples can override global shared examples within its scope.
      });
    
      beforeAll(^{
        // This is run once and only once before all of the examples
        // in this group and before any beforeEach blocks.
      });
    
      beforeEach(^{
        // This is run before each example.
      });
    
      it(@"should do stuff", ^{
        // This is an example block. Place your assertions here.
      });
    
      it(@"should do some stuff asynchronously", ^AsyncBlock {
        // Async example blocks need to invoke done() callback.
        done();
      });
    
      itShouldBehaveLike(@"a shared behavior", @{@"key" : @"obj"});
    
      itShouldBehaveLike(@"another shared behavior", ^{
        // Use a block that returns a dictionary if you need the context to be evaluated lazily,
        // e.g. to use an object prepared in a beforeEach block.
        return @{@"key" : @"obj"};
      });
    
      describe(@"Nested examples", ^{
        it(@"should do even more stuff", ^{
          // ...
        });
      });
    
      pending(@"pending example");
    
      pending(@"another pending example", ^{
        // ...
      });
    
      afterEach(^{
        // This is run after each example.
      });
    
      afterAll(^{
        // This is run once and only once after all of the examples
        // in this group and after any afterEach blocks.
      });
    });
    
    SpecEnd

However, the following line still remains:

      itShouldBehaveLike(@"a shared behavior", @{@"key" : @"obj"});

So I'd expect a failure.  Alas, all of the tests pass!  Including that one…

      -[ThingSpec Thing_a_shared_behavior]
        Test Case '-[ThingSpec Thing_a_shared_behavior]' started.
        Test Case '-[ThingSpec Thing_a_shared_behavior]' passed (0.000 seconds).
    …
      Test Suite 'All tests' finished at 2014-03-31 22:45:22 +0000.
      Executed 6 tests, with 0 failures (0 unexpected) in 0.248 (0.250) seconds

    6 tests; 0 skipped; 0 failures; 0 exceptions; 2 pending

Which I traced to the following code in Specta.m:

    SPTXCTestCase *currentTestCase = SPTCurrentTestCase;
    if (currentTestCase) {
      [currentTestCase recordFailureWithDescription:@"itShouldBehaveLike should not be invoked inside an example block!" inFile:@(fileName) atLine:lineNumber expected:NO];
    } else {
      it(name, ^{
        [currentTestCase recordFailureWithDescription:[NSString stringWithFormat:@"Shared example group \"%@\" does not exist.", name] inFile:@(fileName) atLine:lineNumber expected:NO];
      });
    }

This code does seem a bit absurd, saying if the object is nil call a method on it.  Sure enough, when we get there it's nil in the debugger and the method does nothing.

**Comment by paweldudek** [comment]
This has already been resolved https://github.com/specta/specta/pull/80. @orta yet another one to close :wink:

**Comment by orta** [comment]
Ace.
