### ISSUE TITLE
XCTest does not load test cases unless the 'xctest' branch is used in Podfile

### ISSUE THREAD

**Issue by czhae** [specta/specta#71]
```
platform :ios, 7.0

target :BudgeTests do
  pod 'Expecta'
  pod 'Specta'
end
```
Originally had this to set up a new project. But then I realized that the building test did not pick up the test cases I wrote. After trying out bunch of ways, I explicitly listed the *xctest* branch in Podfile.

```
platform :ios, 7.0

target :BudgeTests do
  pod 'Expecta'
  #pod 'Specta'
  pod 'Specta', git: "https://github.com/specta/specta.git", branch: "xctest"
end
```

After cleaning the workspace, running test started to recognize my test cases. Funny thing is I changed it back to my original listing which is

```
pod 'Specta'
```

instead of

```
pod 'Specta', git: "https://github.com/specta/specta.git", branch: "xctest"
```

and it still works.

I am still trying to figure out what happened.

p.s. - If there is a mailing list for Specta, I will gladly move the conversation over and close the issue. Thanks!

**Comment by orta** [comment]
Fixed :+1:
