### ISSUE TITLE
Usage of AsyncBlock causing frequent (Unexpected SuiteDidStart) errors

### ISSUE THREAD

**Issue by wessmith** [specta/specta#77]
I have been unable to use `AsyncBlock` reliably. When writing tests and running a single spec, it seems to work fine. However, when I run the whole test suite, I frequently get an error like:
```
Test Case '-[MyClass MyClass_testing_some_async_task]' started.
        = All tests
MyClass_testing_some_async_task encountered an error (Unexpected SuiteDidStart)
```

These errors either fail the build as soon as it hits the async spec, or it continues to run.. forever.. running the entire suite over and over and over endlessly until I stop it.

It's worth noting that we have about half of our test suite written in plain old XCTest. I'm not sure if that has anything to do with it or not.

**Comment by orta** [comment]
@tangphillip presuming this is based on the Meetup codebase, does this problem still exist?

**Comment by tangphillip** [comment]
I think we rewrite the test that was failing with another form of asynchrony. So...I can't reproduce this problem any more.

**Comment by orta** [comment]
We have a _lot_ of things like this in the Artsy testing codebases. Going to close for now. If people are seeing this, please chime in.

**Comment by mickeyreiss** [comment]
We've been seeing some instability with `waitUntil` in Braintree-iOS (they are also do not interoperate nicely with KIF). To workaround, I've been migrating slowly towards `XCTestExpectation`s for async tests.
