### ISSUE TITLE
Test delegate methods w/ Specta-Expecta

### ISSUE THREAD

**Issue by james075** [specta/specta#78]
How could I test classes' delegate methods *properly* ?

        expect(viewC).conformTo(@protocol(xProto));

        expect(viewC).respondTo(@selector(xMethod:));
        expect(viewC).respondTo(@selector(xMethod:));
        expect(viewC).respondTo(@selector(xMethod));

e.g with Mock

        id delegateMock = [KWMock mockForProtocol:@protocol(xProto)];
        
        [manager setDelegate:delegateMock];

        NSString *response = @"foo";
        [[[delegateMock shouldEventually] receive] managerRepliedWithResponse:response];
        
        [manager performxMethod];

Thanks in advance!

**Comment by orta** [comment]
These are `expecta` extensions, but you can do some of these, as I've made a [Expecta+OCMock](https://github.com/dblock/ocmock-expecta) lib.
