### ISSUE TITLE
v0.3  - Xcode6 and Swift support

### ISSUE THREAD

**Issue by petejkim** [specta/specta#87]
- [x] replace `^AsyncBlock` with `waitUntil()`
- [x] make it work on xcode6 (still wip)
- [ ] add support for writing specs in swift
- [x] shuffle tests

Branch: https://github.com/specta/specta/tree/0.3-wip

**Comment by orta** [comment]
OK, I'm closing this. A stable 0.3.x is out, I think Swift support is it's own issue. Which I've made: https://github.com/specta/specta/issues/130
