### ISSUE TITLE
Failures not being passed to XCTest in certain threading conditions

### ISSUE THREAD

**Issue by neonichu** [specta/specta#96]
I was just dealing with an issue where a failed expectation was not passed correctly to XCTest, causing the test to still pass.

The issue is that `SPTCurrentTestCase` was actually `nil` here:

<https://github.com/specta/specta/blob/master/src/SPTXCTestCase.m#L141>

What happened was that my code delivered a completion block on a background queue and the current test case was not set for the corresponding thread. 

It seems very easy to miss such a problem, unless one diligently goes through the whole console log. I think there should at least be an assertion in there, so that a non-delivered failure definitely is bubbled up to the user - maybe it might even make sense to look in the main thread's `threadDictionary` for the current test case and use that if the current thread's is `nil`?

**Comment by orta** [comment]
Related: https://github.com/specta/specta/issues/123

**Comment by orta** [comment]
This is merged with #133
